name: Build Pull request
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    name: Node ${{ matrix.node }} sample
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5 # 0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: ⎔ Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: build tina
        env:
          NEXT_PUBLIC_TINA_BRANCH: ${{ secrets.NEXT_PUBLIC_TINA_BRANCH }}
          NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          ALGOLIA_ADMIN_KEY: 'dummy'
          CLOUDINARY_API_SECRET: 'dummy'
          RECAPTCHA_SECRETKEY: 'dummy'
          SENDGRID_API_KEY: 'dummy'
          NEXT_PUBLIC_ALGOLIA_APP_ID: 'dummy'
          NEXT_PUBLIC_ALGOLIA_INDEX_NAME: 'dummy'
          NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY: 'dummy'
          NEXT_PUBLIC_CLOUDINARY_API_KEY: 'dummy'
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: 'dummy'
          NEXT_PUBLIC_RECAPTCHA_SITEKEY: 'dummy'
          NEXT_PUBLIC_URL: 'https://www.nerdfish.be'
        run: pnpm build:tina

      - run: pnpm validate
