name: Quality Gate
on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  NEXT_PUBLIC_TINA_BRANCH: ${{ github.head_ref }}
  NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
  TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
  RESEND_API_KEY: 're_test'
  EMAIL_FROM: 'test'
  NEXT_PUBLIC_URL: 'https://www.nerdfish.be'
  GROQ_API_KEY: 'test'

jobs:
  format:
    name: Format
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./packages/github-actions/install

      - name: Run format
        run: pnpm format

  lint:
    name: Lint
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./packages/github-actions/install

      - name: Build for types
        run: pnpm build:tina

      - name: Run lint
        run: pnpm lint

  typecheck:
    name: TypeCheck
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./packages/github-actions/install

      - name: Build for types
        run: pnpm build:tina

      - name: Cache TypeScript TSBuild Info Files
        id: cache-typescript-tsbuildinfo
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/*-tsbuildinfo.json
          # We use the commit hash as the key to always update the cache as a
          # workaround to this issue:
          # https://github.com/actions/cache/issues/106
          key: ${{ runner.os }}-cache-typescript-tsbuildinfo-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cache-typescript-tsbuildinfo-

      - name: Run TypeScript type check
        run: pnpm run typecheck

  e2e:
    name: E2E
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./packages/github-actions/install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install chromium --with-deps

      - name: Build
        run: pnpm build

      - name: Run Playwright tests
        run: turbo test:e2e --continue
        env:
          SKIP_EMAILS: 'true'

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: apps/web/playwright-report/

      - name: Save PR number
        if: always()
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > prNumber

      - name: Upload prNumber
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: prNumber
          path: prNumber
