name: Build Pull request
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_TINA_BRANCH: ${{ github.head_ref }}
      NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
      TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
      RECAPTCHA_SECRETKEY: 'test'
      RESEND_API_KEY: 're_test'
      EMAIL_FROM: 'test'
      NEXT_PUBLIC_RECAPTCHA_SITEKEY: 'test'
      NEXT_PUBLIC_URL: 'https://www.nerdfish.be'
      GROQ_API_KEY: 'test'

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: ⎔ Setup node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Run TypeScript type check
        run: pnpm checks
