name: PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 📥 Download sanity deps
        run: |
          cd studio
          npm install

      - name: 🔬 Validate
        run: npm run validate
